In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.DataFrame(columns=["ACWI", "IUII", "SPLG"])

df.loc["pesos_objetivo"] = [0.30, 0.30, 0.40]

df.loc["precio_t=0"] = [91.25, 20.21, 51.14]

df

                 ACWI   IUII   SPLG
pesos_objetivo   0.30   0.30   0.40
precio_t=0      91.25  20.21  51.14

In [21]:
df.loc["num_stock"] = np.floor((200_000 * df.loc["pesos_objetivo"]) / df.loc["precio_t=0"])
df

                  ACWI     IUII     SPLG
pesos_objetivo    0.30     0.30     0.40
precio_t=0       91.25    20.21    51.14
num_stock       657.00  2968.00  1564.00

In [22]:
df2 = pd.DataFrame(columns=["ACWI", "IUII", "SPLG"])

df2.loc["precio_t=6m"] = [87.45, 20.17, 77.15]

df2.loc["valor_posicion"] = df.loc["num_stock"] * df2.loc["precio_t=6m"]

df2.loc["pesos_actuales"] = df2.loc["valor_posicion"] / sum(df2.loc["valor_posicion"])

df2

                        ACWI          IUII           SPLG
precio_t=6m        87.450000     20.170000      77.150000
valor_posicion  57454.650000  59864.560000  120662.600000
pesos_actuales      0.241425      0.251551       0.507024

In [24]:
sum(df2.loc["valor_posicion"])

237981.81

In [29]:
df2.loc["Revalanceo C/V"] = np.floor((df.loc["pesos_objetivo"] - df2.loc["pesos_actuales"]) * sum(df2.loc["valor_posicion"]) /df2.loc["precio_t=6m"])

df2

                        ACWI          IUII           SPLG
precio_t=6m        87.450000     20.170000      77.150000
valor_posicion  57454.650000  59864.560000  120662.600000
pesos_actuales      0.241425      0.251551       0.507024
Revalanceo C/V    159.000000    571.000000    -331.000000

In [ ]:
# Comprobación rapida
(
    df.loc["num_stock"] + 
    df2.loc["Revalanceo C/V"]
) * df2.loc["precio_t=6m"]/sum(df2.loc["valor_posicion"])

ACWI    0.299851
IUII    0.299946
SPLG    0.399719
dtype: float64